# Default initial positions for ergoCub's ros2_control fake system

initial_positions:
  l_ankle_pitch: 0
  l_ankle_roll: 0
  l_elbow: 0
  l_hip_pitch: 0
  l_hip_roll: 0
  l_hip_yaw: 0
  l_index_add: 0
  l_index_dist: 0
  l_index_prox: 0
  l_knee: 0
  l_middle_dist: 0
  l_middle_prox: 0
  l_pinkie_dist: 0
  l_pinkie_prox: 0
  l_ring_dist: 0
  l_ring_prox: 0
  l_shoulder_pitch: 0
  l_shoulder_roll: 0
  l_shoulder_yaw: 0
  l_thumb_add: 0
  l_thumb_dist: 0
  l_thumb_prox: 0
  l_wrist_pitch: 0
  l_wrist_roll: 0
  l_wrist_yaw: 0
  neck_pitch: 0
  neck_roll: 0
  neck_yaw: 0
  r_ankle_pitch: 0
  r_ankle_roll: 0
  r_elbow: 0
  r_hip_pitch: 0
  r_hip_roll: 0
  r_hip_yaw: 0
  r_index_add: 0
  r_index_dist: 0
  r_index_prox: 0
  r_knee: 0
  r_middle_dist: 0
  r_middle_prox: 0
  r_pinkie_dist: 0
  r_pinkie_prox: 0
  r_ring_dist: 0
  r_ring_prox: 0
  r_shoulder_pitch: 0
  r_shoulder_roll: 0
  r_shoulder_yaw: 0
  r_thumb_add: 0
  r_thumb_dist: 0
  r_thumb_prox: 0
  r_wrist_pitch: 0
  r_wrist_roll: 0
  r_wrist_yaw: 0
  torso_pitch: 0
  torso_roll: 0
  torso_yaw: 0
