# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    l_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    r_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    l_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    r_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    torso_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

l_arm_controller:
  ros__parameters:
    joints:
      - l_shoulder_roll
      - l_shoulder_yaw
      - l_elbow
      - l_wrist_yaw
      - l_wrist_roll
      - l_wrist_pitch
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
r_arm_controller:
  ros__parameters:
    joints:
      - r_shoulder_roll
      - r_shoulder_yaw
      - r_elbow
      - r_wrist_yaw
      - r_wrist_roll
      - r_wrist_pitch
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
l_leg_controller:
  ros__parameters:
    joints:
      - l_hip_pitch
      - l_hip_roll
      - l_hip_yaw
      - l_knee
      - l_ankle_pitch
      - l_ankle_roll
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
r_leg_controller:
  ros__parameters:
    joints:
      - r_hip_pitch
      - r_hip_roll
      - r_hip_yaw
      - r_knee
      - r_ankle_pitch
      - r_ankle_roll
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
head_controller:
  ros__parameters:
    joints:
      - neck_pitch
      - neck_roll
      - neck_yaw
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
torso_controller:
  ros__parameters:
    joints:
    - torso_pitch
    - torso_roll
    - torso_yaw
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
