# Default initial positions for iCub's ros2_control fake system

initial_positions:
  l_ankle_pitch: 0
  l_ankle_roll: 0
  l_elbow: 0
  l_hip_roll: 0
  l_hip_yaw: 0
  l_knee: 0
  l_shoulder_roll: 0
  l_shoulder_yaw: 0
  l_wrist_pitch: 0
  l_wrist_prosup: 0
  l_wrist_yaw: 0