# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  l_ankle_pitch:
    has_velocity_limits: true
    max_velocity: 120.0
    has_acceleration_limits: false
    max_acceleration: 0
  l_ankle_roll:
    has_velocity_limits: true
    max_velocity: 120.0
    has_acceleration_limits: false
    max_acceleration: 0
  l_elbow:
    has_velocity_limits: true
    max_velocity: 120.0
    has_acceleration_limits: false
    max_acceleration: 0
  l_hip_roll:
    has_velocity_limits: true
    max_velocity: 120.0
    has_acceleration_limits: false
    max_acceleration: 0
  l_hip_yaw:
    has_velocity_limits: true
    max_velocity: 120.0
    has_acceleration_limits: false
    max_acceleration: 0
  l_knee:
    has_velocity_limits: true
    max_velocity: 120.0
    has_acceleration_limits: false
    max_acceleration: 0
  l_shoulder_roll:
    has_velocity_limits: true
    max_velocity: 120.0
    has_acceleration_limits: false
    max_acceleration: 0
  l_shoulder_yaw:
    has_velocity_limits: true
    max_velocity: 120.0
    has_acceleration_limits: false
    max_acceleration: 0
  l_wrist_pitch:
    has_velocity_limits: true
    max_velocity: 120.0
    has_acceleration_limits: false
    max_acceleration: 0
  l_wrist_prosup:
    has_velocity_limits: true
    max_velocity: 120.0
    has_acceleration_limits: false
    max_acceleration: 0
  l_wrist_yaw:
    has_velocity_limits: true
    max_velocity: 120.0
    has_acceleration_limits: false
    max_acceleration: 0