# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    torso_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm_controller:
  ros__parameters:
    joints:
      - l_shoulder_pitch
      - l_shoulder_roll
      - l_shoulder_yaw
      - l_elbow
      - l_wrist_prosup
      - l_wrist_pitch
      - l_wrist_yaw
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_arm_controller:
  ros__parameters:
    joints:
      - r_shoulder_pitch
      - r_shoulder_roll
      - r_shoulder_yaw
      - r_elbow
      - r_wrist_prosup
      - r_wrist_pitch
      - r_wrist_yaw
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
left_leg_controller:
  ros__parameters:
    joints:
    - l_hip_pitch
    - l_hip_roll
    - l_hip_yaw
    - l_knee
    - l_ankle_pitch
    - l_ankle_roll
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_leg_controller:
  ros__parameters:
    joints:
    - r_hip_pitch
    - r_hip_roll
    - r_hip_yaw
    - r_knee
    - r_ankle_pitch
    - r_ankle_roll
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
head_controller:
  ros__parameters:
    joints:
    - neck_pitch
    - neck_roll
    - neck_yaw
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
torso_controller:
  ros__parameters:
    joints:
    - torso_pitch
    - torso_roll
    - torso_yaw
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity